apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudprofile.yaml
- controller-registration.yaml
- project.yaml
- secret-backup.yaml
- secretbinding.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-cilium/v1.24.0/example/controller-registration.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/v1.33.0/example/controller-registration.yaml

patchesStrategicMerge:
- patch-controller-registrations.yaml

patches:
- patch: |
    apiVersion: core.gardener.cloud/v1beta1
    kind: ControllerDeployment
    metadata:
      name: networking-calico
    type: helm
    providerConfig:
      values:
        image:
          # https://github.com/stackitcloud/gardener-extension-networking-calico/tree/feature/ipv6-support
          repository: ghcr.io/stackitcloud/gardener-extension-networking-calico/networking-calico
          tag: 74ec38c7e851d54d262df1beb12634800ea92646
- target:
    group: core.gardener.cloud
    kind: ControllerRegistration
    name: provider-local
  patch: |
    - op: add
      path: /spec/resources/-
      value:
        kind: Extension
        type: local-ext-seed
        lifecycle:
          reconcile: BeforeKubeAPIServer
          delete: AfterKubeAPIServer
          migrate: AfterKubeAPIServer
        workerlessSupported: true
    - op: add
      path: /spec/resources/-
      value:
        kind: Extension
        type: local-ext-shoot
        workerlessSupported: true
