config:
  seedConfig:
    spec:
      networks:
        ipFamilies:
        - IPv4
        - IPv6
        nodes: 172.18.0.0/16
        # Those CIDRs must match those specified in the kind Cluster configuration.
        pods: 10.1.0.0/16
        services: 10.2.0.0/16
        shootDefaults:
          ipFamilies:
          - IPv4
          - IPv6
          pods: fd00:10:3::/56
          services: fd00:10:4::/112

